export const Names = [
            'tiger', 'doctor', 'teacher', 'lucifer', 'doom', 'hero', 'star', 'batman', 'superman', 'ironman', 
            'looter', 'kooper', 'parrot', 'strange', 'brain streamer', 'razor', 'pewpew', 'brave'
            ,'William','Phelps'
, 'Austin','Moss'
,'Barry' ,'Vaughn'
,'Clifton','Francis'
,'Jessie ','Morris'
,'Orlando ','Meyer'
,'Glenn','Webb'
,'Eric ','Padilla'
,'Jay ','Morales'
,'Clay ','Santiago'
,'Dominic ','Phillips'
,'Daryl ','Adams'
,'Laurence ','Jackson'
,'Felix ','Tucker'
,'Duane ','Bowen'
,'Hector ','Hopkins'
,'Woodrow ','Bennett'
,'Marion ','Woods'
,'Philip ','Chandler'
,'Dewey ','Stone'
,'Alex ','Cook'
,'Alonzo ','Stewart'
,'Kim ','Mullins'
,'Jose ','Montgomery'
,'Earl ','Shelton'
,'Everett ','Aguilar'
,'Gerard ','Duncan'
,'Derek ','Graham'
,'Kyle ','Parks'
,'Norman ','Ortiz'
]